cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('cart', views.cart_detail, name='cart_detail'),
    path('add/<int:produit_id>/', views.ajouter_cart, name='cart_add'),
    path('update/<int:produit_id>/', views.update_cart, name='cart_update'),
    
    
    path('remove/<int:produit_id>', views.supprimer_cart, name='cart_remove'),
]

commandes/urls.py
from django.urls import path
from . import views

app_name = 'commandes'

urlpatterns = [
    path('creer', views.creer_commande, name='creer_commande'),
   
    path('ajax/load-quartiers', views.load_quartiers, name='ajax_load_quartiers'),
    path('mes-commandes', views.commandes_user, name='mes_commandes'),
    path('<int:commande_id>', views.commandes_detail, name='detail_commande')
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

marche/urls.py
from django.urls import path
from . import views

app_name = 'marche'

urlpatterns = [
    path('', views.accueil, name='accueil'),
	path('search', views.post_search, name='post_search'),
	#path('<slug:categorie_slug>/', views.produits_par_categorie, name='produit_par_categorie'),
	path('<slug:supcategorie_slug>', views.produits_par_supcategorie, name='produit_par_supcategorie'),
	path('<int:id>/<slug:slug>', views.produit_detail, name='produit_detail'),
	

]

samamarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users import views as user_views

from users import views

#from users.views import RegistrationView, ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('marche.urls')),

    path('cart/', include('cart.urls')),

    path('commandes/', include('commandes.urls')),

    path('coupons/', include('coupons.urls')),

    #path('register/', user_views.register, name='register'),
    #path('profile/', user_views.profile, name='profile'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    #path('commandes/login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    #path('register/', RegistrationView.as_view(), name='register'),
    path('register/', user_views.register, name='register'),
    #path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/profile', user_views.profile, name='profile'),
    #path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('accounts/login/', user_views.signin, name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('accounts/password_change/', user_views.change_password, name='password_change'),
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/done/', user_views.change_password_done, name='password_change_done'),

    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset'),
    path('password_reset/', user_views.password_reset_request, name='password_reset'),
    path('password_reset_instructions/', user_views.instructions_reset_page, name='passwordinstructions'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', user_views.password_reset_confirme, name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]
handler404 = 'marche.views.error_404'

handler500 = 'marche.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class CartProduitForm(forms.Form):
    quantite = forms.IntegerField(initial = 1, validators=[MinValueValidator(1),
                                       MaxValueValidator(100)], widget=forms.TextInput(attrs={'min':1,'max': '100','type': 'number'}))
    update_qt = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST
from marche.models import Produit, Info, HoraireLivraison
from .cart import Cart
from .forms import CartProduitForm
from marche.forms import SearchForm
from django.http import JsonResponse
from users.models import User
from coupons.forms import CouponApplyForm
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
import json
from django.forms.models import model_to_dict
from django.conf import settings
from django.contrib import messages
# Create your views here.
#Informations
info = Info.objects.all()[:1]
searchform = SearchForm()



@require_POST
def ajouter_cart(request, produit_id):
    cart = Cart(request)
    carte = request.session.get(settings.CART_SESSION_ID)
    #produit = get_object_or_404(Produit, id=produit_id)
    produit = Produit.objects.get(id=produit_id)
    #cart = serializers.serialize('json', [Cart]) 
    form = CartProduitForm(request.POST)
    if request.method == 'POST' and request.is_ajax():
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(produit=produit,
                    quantite=cd['quantite'],
                    update_quantite=cd['update_qt']
                    )
    
    #carte = serializers.serialize('json', cart)
    message = 'Le produit est ajouté avec succès'
    return JsonResponse({'status': 'success', 'message':message})
    #return redirect(request.META.get('HTTP_REFERER'))


def update_cart(request, produit_id):
    cart = Cart(request)
    produit = get_object_or_404(Produit, id=produit_id)
    form = CartProduitForm(request.POST)
    if request.method == 'POST' and request.is_ajax():
        if form.is_valid():
            cd = form.cleaned_data
            cart.maj_cart(produit=produit,
                    quantite=cd['quantite'],
                    update_quantite=cd['update_qt']
                    )
    return JsonResponse({'status': 'success'})


def supprimer_cart(request, produit_id):
    cart = Cart(request)
    produit = get_object_or_404(Produit, id=produit_id)
    cart.remove(produit)
    return redirect('cart:cart_detail')

"""
def supprimer_cart(request, produit_id):
    cart = Cart(request)
    produit = get_object_or_404(Produit, id=produit_id)
    cart.remove(produit)
    return JsonResponse({'status': 'success'})
"""

def cart_detail(request):
    cart = Cart(request)
    user = request.user
    cart.supp_no_available()
    cart.maj_prices()
    for item in cart:
        
        itemer = item['produit'].disponibilite
        item['update_quantite_form'] = CartProduitForm(
        initial={'quantite': item['quantite'],
        'update_qt': True})
    coupon_apply_form = CouponApplyForm()
    context = {
        'cart': cart,
        'itemer': cart,
        'user': user,
        'info': info,
        'searchform': searchform,
        'coupon_apply_form': coupon_apply_form,
        'horaire_livraison': HoraireLivraison.objects.all()[:1]
    }
    return render(request, 'cart/cart_detail.html', context)

cart/templates/cart/cart_detail.html
{% extends "marche/main.html" %}
{% load static %}
{% load humanize %}
{% block carousel %}
{% endblock %}
{% block content %}
{% if cart|length > 0 %}
    <div class="container to_register cart_bigs aeftcu">
        <div class="row">
            <div class="col-md-12">
        <h3 class="text-dark">Votre Panier</h3>
        <h5 class="text-horaire">Prochaine livraison : <span class="horaire-livraison" style="color: rgb(0, 102, 79)!important;">{% for horaire in horaire_livraison %}{{ horaire.date_prochaine_livraison }}{% endfor %}</span></h5>
        <div class="box-element" id="box-produit">

            <br>
            <table class="table">
                <tr>
                    <th><h5>Articles: <strong id="cartvv">{{ cart | length }}</strong></h5></th>
                    {% if cart.coupon %}
                        <th><h5>Code promo: <strong>{{ cart.coupon.code }} ({{ cart.coupon.reduction }}% off)</strong></h5></th>
                        <th><h5>Total:<strong class="cf_plophyy" id="cartvve"> {{ cart.get_prix_total | intcomma }} FCFA</strong> <strong>{{ cart.get_prix_total_apres_reduction | intcomma }} FCFA</strong></h5></th>
                    {% else %}
                        <th><h5>Total:<strong class="" id="cartvve"> {{ cart.get_prix_total | intcomma }} FCFA</strong></h5></th>
                    {% endif %}
                    <th class="cart-commander">
                        <a  style="float:right;" class="btn btn-success" href="{% url "commandes:creer_commande" %}">Commander</a>
                    </th>
                </tr>
            </table>
            
        </div>

        <br>
        <div class="box-element">
			<div class="cart-row">
				<div style="flex:1" class="flex-cart"></div>
                <div style="flex:2" class="flex-cart"><strong>Produit</strong></div>
                <div style="flex:1" class="flex-cart">Supprimer</div>
				<div style="flex:1" class="flex-cart"><strong>P.U/Qté</strong></div>
				<div style="flex:1" class="flex-cart"><strong>Qté</strong></div>
				<div style="flex:1" class="flex-cart"><strong>Total</strong></div>
    		</div>
			{% for item in cart %}
			<div class="cart-row">
                {% if item.produit.image %}
				    <div style="flex:1"><img class="row-image" src="{{ item.produit.image.url }}"></div>
                {% else %}
                    <div style="flex:1"><img class="row-image" src="{% static 'images/courge.jpg' %}"></div>
                {% endif %}
                <div style="flex:2"><p class="afrtif">{{item.produit}}</p></div>
                <div style="flex:1"><a class="delete_prod_cart afrtif" href="{% url 'cart:cart_remove' item.produit.id %}" id=""aria-haspopup="true" data-id="{{ item.produit.id }}" aria-expanded="false">
                <i class="fas fa-shopping-cart"></i></li></a>
                        
                </div>
                    
				<div style="flex:1"><p class="afrtif">{{item.prix | intcomma }} FCFA/{{ item.produit.unite }}</p></div>
                <div style="flex:1">
    
                    <form action="{% url "cart:cart_update" item.produit.id %}" method="post" class="form-order-cart" data-id="{{ item.produit.id }}">
                        {{ item.update_quantite_form.quantite }}
                        {{ item.update_quantite_form.update_quantite }}
                        <input type="submit" value="Update" class="update_prod_qt">
                        {% csrf_token %}
                    </form>
                            
                </div>
				<div style="flex:1"><p class="afrtif">{{item.prix_total | intcomma }} FCFA</p></div>
            </div>
                
            {% endfor %}
            <p class="afrtif">Avez-vous un code promo ?</p>
            <form action="{% url "coupons:apply" %}" method="post">
                {{ coupon_apply_form }}
                <input type="submit" value="Appliquer" class="btn btn-success">
                {% csrf_token %}
            </form>

            <p class="text-right">
                <a href="{% url "marche:accueil" %}" class="btn btn-light light">Continuez vos achats</a>
                <a class="btn btn-success" href="{% url "commandes:creer_commande" %}">Commander</a>
            </p>

            </div>
        </div>
    </div>
    </div>

    <div class="container to_register cart_mins">
        <div class="row">
            <div class="col-12">
                <h3 class="text-dark">Votre panier</h3>
                <h5 class="text-horaire">Prochaine livraison : <span class="horaire-livraison" style="color: rgb(0, 102, 79)!important;">{% for horaire in horaire_livraison %}{{ horaire.date_prochaine_livraison }}{% endfor %}</span></h5>
                <h5>Articles: <strong>{{ cart | length }}</strong></h5>
                {% if cart.coupon %}
                    <h5>Code promo: <strong>{{ cart.coupon.code }} ({{ cart.coupon.reduction }}% off)</strong></h5>
                    <h5>Total:<strong class="cf_plophyy"> {{ cart.get_prix_total | intcomma }} FCFA</strong> <strong>{{ cart.get_prix_total_apres_reduction | intcomma }} FCFA</strong></h5>
                {% else %}
                    <h5>Total:<strong> {{ cart.get_prix_total | intcomma }} FCFA</strong></h5>
                {% endif %}
                {% for item in cart %}
                <div class="row cart_prod_block">
                        {% if item.produit.image %}
                            <div class="col-4"><img class="row-image" src="{{ item.produit.image.url }}"></div>
                        {% else %}
                            <div class="col-4"><img class="row-image" src="{% static 'images/courge.jpg' %}"></div>
                        {% endif %}
                        <div class="col-8">
                            <h6 class="afrtif">{{item.produit}}</h6>
                            <small class="text-muted afrtif">{{ item.prix | intcomma }} FCFA - {{ item.produit.unite }}</small>
                            <p><small class="text-muted afrtif">Total :{{ item.prix_total | intcomma }} FCFA</small></p>
                            <div class="col-12">
                            <div class="row">
                                <div class="col-8">
                                    <form action="{% url "cart:cart_update" item.produit.id %}" method="post" class="form-order-cart" data-id="{{ item.produit.id }}">
                                        <span class="afrtif">Qté</span>{{ item.update_quantite_form.quantite }}
                                        {{ item.update_quantite_form.update_quantite }}
                                        <input type="submit" value="Update" class="update_prod_qt">
                                        {% csrf_token %}
                                    </form>
                                </div>
                                <div class="col-2" class="delete_prod_cart">
                                    <i class="delete_prod_cart"></i>
                                </div>
                            </div>
                            </div>
                            
                        </div>
                    
                </div>
                {% endfor %}
                <p class="afrtif">Entrer votre code promo:</p>
                <form action="{% url "coupons:apply" %}" method="post">
                    {{ coupon_apply_form }}
                    <input type="submit" value="Appliquer" class="btn btn-success">
                    {% csrf_token %}
                </form>

                <p class="">
                    <a href="{% url "marche:accueil" %}" class="btn btn-light light">Continuez vos achats</a>
                    <a class="btn btn-success" href="{% url "commandes:creer_commande" %}">Commander</a>
                </p>
            </div>
        </div>
    </div>
{% else %}
    <div class="col-md-12" style="text-align: center;">
        <i class="bx bxs-cart icon-single empty-icon-cart" style="font-size: 6rem;"></i>
        <p style="font-size: 1.5rem;">Votre panier est vide</p>
        <a href="{% url 'marche:accueil' %}" class="btn btn-primary waves-effect waves-light">Faire vos courses</a>
    </div>
{% endif %}
    
{% endblock %}