cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('cart', views.cart_detail, name='cart_detail'),
    path('add/<int:produit_id>/', views.ajouter_cart, name='cart_add'),
    path('update/<int:produit_id>/', views.update_cart, name='cart_update'),
    
    
    path('remove/<int:produit_id>', views.supprimer_cart, name='cart_remove'),
]

marche/urls.py
from django.urls import path
from . import views

app_name = 'marche'

urlpatterns = [
    path('', views.accueil, name='accueil'),
	path('search', views.post_search, name='post_search'),
	#path('<slug:categorie_slug>/', views.produits_par_categorie, name='produit_par_categorie'),
	path('<slug:supcategorie_slug>', views.produits_par_supcategorie, name='produit_par_supcategorie'),
	path('<int:id>/<slug:slug>', views.produit_detail, name='produit_detail'),
	

]

samamarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users import views as user_views

from users import views

#from users.views import RegistrationView, ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('marche.urls')),

    path('cart/', include('cart.urls')),

    path('commandes/', include('commandes.urls')),

    path('coupons/', include('coupons.urls')),

    #path('register/', user_views.register, name='register'),
    #path('profile/', user_views.profile, name='profile'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    #path('commandes/login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    #path('register/', RegistrationView.as_view(), name='register'),
    path('register/', user_views.register, name='register'),
    #path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/profile', user_views.profile, name='profile'),
    #path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('accounts/login/', user_views.signin, name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('accounts/password_change/', user_views.change_password, name='password_change'),
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/done/', user_views.change_password_done, name='password_change_done'),

    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset'),
    path('password_reset/', user_views.password_reset_request, name='password_reset'),
    path('password_reset_instructions/', user_views.instructions_reset_page, name='passwordinstructions'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', user_views.password_reset_confirme, name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]
handler404 = 'marche.views.error_404'

handler500 = 'marche.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marche/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class SupCategorie(models.Model):
    nom = models.CharField(max_length=50, db_index=True)
    slug = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to = 'supcategories/%y/%m/%d', blank=True)
    description = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_maj = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date_maj',)
        verbose_name = 'supcategories'
        verbose_name_plural = 'supcategories'

    def __str__(self):
        return self.nom

class Categorie(models.Model):
    nom = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    sup_categorie = models.ForeignKey(SupCategorie, related_name='categories', on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'categories/%y/%m/%d', blank=True)
    description = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_maj = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date_creation',)
        verbose_name = 'categorie'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('marche:produit_par_categorie', args=[self.slug])

    def get_produits(self):
        return Produit.objects.filter(categorie=self)



class Produit(models.Model):
    categorie = models.ForeignKey(Categorie, related_name='produits', on_delete=models.CASCADE)
    nom = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to = 'produits/%y/%m/%d', blank=True)
    description = models.CharField(max_length=200, default="Détails de...", null=True, blank=True)
    provenance = models.TextField(blank=True)
    prix = models.IntegerField()
    unite = models.CharField(max_length=30, blank=True)
    disponibilite = models.BooleanField(default=True)
    stock = models.IntegerField(default=1, null=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_maj = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('date_maj',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('marche:produit_detail', args=[self.id, self.slug])

    
class Info(models.Model):
    adresse = models.CharField(max_length=100)
    email = models.EmailField()
    telephone = models.CharField(max_length=30)
    description = models.TextField()
    for_business = models.TextField()
    free_liv = models.TextField()


class Homeslide(models.Model):
    nom = models.CharField(max_length=30, default='Slide name')
    image = models.ImageField(upload_to = 'homeslide/%y/%m/%d', blank=True)
    lien = models.CharField(max_length=20)

class HoraireLivraison(models.Model):
    date_prochaine_livraison = models.DateField()

marche/forms.py
from django import forms
from .models import Produit

class SearchForm(forms.Form):
    query = forms.CharField(widget= forms.TextInput
                           (attrs={'class':'form-control',
				                    'id':'some_id',
                                    'label':'',
                                    'placeholder': "Envie d'un légume frais ?"}), label='')

marche/views.py
from django.shortcuts import render, get_object_or_404
from .models import Produit, Categorie, SupCategorie, Info, Homeslide
from cart.forms import CartProduitForm
from cart.cart import Cart
from .forms import SearchForm
from django.contrib.postgres.search import SearchVector

# Create your views here.
searchform = SearchForm()

#Informations


def accueil(request, categorie_slug=None):
    #legume = Produit.objects.filter(categorie.nom=='legumes')
    #Get the fruits
    fruits = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='fruits')[:7]

    #Recuperer les legumes
    legumes = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='legumes')[:7]

    #Recuperer les poissons
    poissons = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='poissons')[:7]

    #Recuperer les viandes
    viandes = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='viandes')[:7]

    #Recuperer les produits epiciers
    epicerie = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='epicerie')[:7]

    #Recuperer les produits de beauté
    beaute = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='beaute')[:7]

    #Recuperer les produits de bébé
    bebe = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='bebe')[:7]

    #Recuperer les produits de vaisselle
    vaisselle = Produit.objects.all().filter(disponibilite=True, categorie__sup_categorie__slug='vaisselle')[:7]
   
    #Categories
    categories = Categorie.objects.all()

    cat_legumes = SupCategorie.objects.filter(slug='legumes')
    cat_fruits = SupCategorie.objects.filter(slug='fruits')
    cat_poissons = SupCategorie.objects.filter(slug='poissons')
    cat_viandes = SupCategorie.objects.filter(slug='viandes')
    cat_epicerie = SupCategorie.objects.filter(slug='epicerie')
    cat_beaute = SupCategorie.objects.filter(slug='beaute')
    cat_bebe = SupCategorie.objects.filter(slug='bebe')
    cat_vaisselle = SupCategorie.objects.filter(slug='vaisselle')
   
    #Slides
    homeslides = Homeslide.objects.all()

    info = Info.objects.all()
    #Cart add product form
    cart_produit_form = CartProduitForm()
    cart = Cart(request)

    context = {
        'homeslides' : homeslides,
        'legumes': legumes,
        'fruits': fruits,
        'poissons': poissons,
        'viandes': viandes,
        'epiecerie': epicerie,
        'bebe': bebe,
        'beaute': beaute,
        'vaisselle': vaisselle,
        'cart_produit_form': cart_produit_form,
        'cart': cart,
        'categories': categories,
        'searchform': searchform,
        'info': info,
        'cat_legumes': cat_legumes,
        'cat_fruits': cat_fruits,
        'cat_poissons': cat_poissons,
        'cat_viandes': cat_viandes,
        'cat_epicerie': cat_epicerie,
        'cat_bebe': cat_bebe,
        'cat_beaute': cat_beaute,
        'cat_vaisselle': cat_vaisselle,
        'info': info
    }

    
    return render(request, 'marche/main.html', context)


def produits_par_categorie(request, categorie_slug=None):
    categorie = None
    categories = Categorie.objects.all()
    produits = Produit.objects.filter(disponibilite=True)
    info = Info.objects.all()
    if categorie_slug:
        categorie = get_object_or_404(Categorie, slug=categorie_slug)
        produits = produits.filter(categorie=categorie)
    
    #Cart add product form
    cart_produit_form = CartProduitForm()
    cart = Cart(request)

    context = {
        'categorie': categorie,
        'categories': categories,
        'produits': produits,
        'cart_produit_form_cat': cart_produit_form,
        'cart': cart,
        'info': info,
    }
    return render(request, 'marche/categorie.html', context)
    

def produits_par_supcategorie(request, supcategorie_slug=None):
    supcategorie = None
    supcategories = SupCategorie.objects.all()
    categorie = Categorie.objects.all()
    produits = Produit.objects.filter(disponibilite=True)
    info = Info.objects.all()
    if supcategorie_slug:
        supcategorie = get_object_or_404(SupCategorie, slug=supcategorie_slug)
        categorie = categorie.filter(sup_categorie__slug=supcategorie_slug)
        produits = produits.filter(categorie__sup_categorie__slug=supcategorie_slug, disponibilite=True)
    
    #Cart add product form
    cart_produit_form = CartProduitForm()
    cart = Cart(request)

    context = {
        'supcategorie': supcategorie,
        'supcategories': supcategories,
        'categorie': categorie,

        'produits': produits,
        'cart_produit_form_cat': cart_produit_form,
        'cart': cart,
        'searchform': searchform,
        'info': info,
    }
    return render(request, 'marche/supcategorie.html', context)

def produit_detail(request, id, slug):
    cart = Cart(request)
    produit = get_object_or_404(Produit, id=id, slug=slug, disponibilite=True)
    cart_produit_form = CartProduitForm()
    info = Info.objects.all()
    context = {
        'produit': produit,
        'cart_produit_form_cat': cart_produit_form,
        'searchform': searchform,
        'cart': cart
    }
    return render(request, 'marche/detail.html', context)



#Search product
def post_search(request):
    cart = Cart(request)
    cart_produit_form = CartProduitForm()
    info = Info.objects.all()
    query = None
    results = []
    searchform = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Produit.objects.annotate(
                search = SearchVector('nom')
            ).filter(search=query, disponibilite=True)
    context = {
        'results': results,
        'cart': cart,
        'cart_produit_form': cart_produit_form,
        'searchform': searchform,
        'info': info,
        'query': query
    }
    return render(request, 'marche/recherche.html',context)


def error_404(request, exception):
        context = {}
        return render(request,'marche/404.html', context)
        

def error_500(request, *args, **argv):
        context = {}
        return render(request,'marche/500.html', context)

marche/templates/marche/categorie.html
{% extends 'marche/main.html' %}
{% load humanize %}
{% load static %}

{% block carousel %}
{% endblock %}
{% block content %}

    <!-- Legumes block -->
    <div class="container desc-categ aeftcu">
        <div class="row">
            <div class="col-md-12">
              <ul  class="list-group">
                <li class=" d-flex justify-content-between lh-condensed categ">
                  <h2 class="text-dark">Les légumes</h2>
                  <span class="see-all-prod">Voir tous</span>
                </li>
              </ul>
              <p class="lead">Plus de 60 horticulteurs partenaires au Sénégal. De la fraîcheur dans votre assiette.</p>
            </div>
          </div>
        </div>
    </div>
  

    <div class="py-5 lkight">
        <div class="container produit"> 
            <div class="row">   
            
                {% for produit in produits %} 
                <div class="col-md-2 col-xs-3 col-sm-3 col-6">
                    <img src="{% static 'images/courge.jpg' %}" alt="" class="img img-responsive produit-categorie w-100">
                    <h5 class="">{{ produit.nom }}</h5>
                    <span class="">{{ produit.prix | intcomma }} FCFA/{{ produit.prix | intcomma }}</span>
                    
                    <form action="{% url "cart:cart_add" produit.id %}" method="post" class="form-order">
                        {{ cart_produit_form_cat }}
                        {% csrf_token %}
                        <input type="submit" value="ACHETER">
                    </form>   
                </div>
                {% endfor %}
        
        
            </div>
        </div> 
        
       
    </div>
    
    <!--End legumes block-->

    <div id="main" class="product-list">
        <h1>
            {% if categorie %}{{ categorie.nom }}
                {% else %}Products
            {% endif %}
        </h1>
        {% for produit in produits %}
        <div class="item">
        <a href="{{ produit.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}{%
        else %}{% endif %}">
        </a>
        <a href="{{ produit.get_absolute_url }}">{{ produit.nom }}</a>
        <br>
        ${{ produit.prix }}
        </div>
        {% endfor %}
    </div>
       
{% endblock %}

marche/templates/marche/detail.html
{% extends 'marche/main.html' %}
{% load humanize %}
{% load static %}
{% block carousel %}
{% endblock %}

{% block content %}

<div class="container aeftcu">

  <div class="row">
    <div class="col-md-4 mb-4 mb-md-0">
      {% if produit.image %}
        <img src="{{ produit.image.url }}" class="w-100bdec" id=""w-100bdec" alt="" style="width: 90%;">
      {% else %}
        <img src="{% static 'images/courge.jpg' %}" class="w-100bdec" id=""w-100bdec" alt="" style="width: 90%;">
      {% endif %}

    </div>
    <div class="col-md-8">

      <h5>{{ produit.nom }}</h5>
      <p><span class="mr-1"><strong>{{ produit.prix }} FCFA</strong></span></p>

      <p class="pt-1">{{ produit.description }}</p>
      
      <div class="table-responsive">
        <table class="table table-sm table-borderless mb-0">
          <tbody>
            <tr>
              <th class="pl-0 w-25" scope="row"><strong>Provenance</strong></th>
              <td>{{ produit.provenance }}</td>
            </tr>
            
          </tbody>
        </table>
      </div>
      <hr>
      <form action="{% url "cart:cart_add" produit.id %}" method="post" class="form-order" data-id="{{ produit.id }}" >
        {{ cart_produit_form_cat }}
        {% csrf_token %}
        <a data-id="{{ produit.id }}" class="acheter-produit"><button>ACHETER</button></a>
    </form>
    </div>
  </div>

</div>
<!--Section: Block Content-->

{% endblock %}

marche/templates/marche/recherche.html
{% extends 'marche/main.html' %}
{% load humanize %}
{% load static %}
{% block carousel %}
{% endblock %}
{% block content %}

<div class="lkight aeftcu">
    <div class="container produit">
        <div class="row">
            {% for produit in results %}
            <div class="col-md-2 lkightpro">
                <img src="{{ produit.image.url }}" class="w-100ce w-100cee" alt="">
                <h5 class="my-3">{{ produit.nom }}</h5>
                <span class="my-3">{{ produit.prix | intcomma }} FCFA/{{ produit.unite }}</span>
                
                <form action="{% url "cart:cart_add" produit.id %}"  method="post" data-id="{{ produit.id }}" class="form-order" id="form">
                    {{ cart_produit_form }}
                    {% csrf_token %}
                    <!--<button type="submit" data-id="{{ legume.id }}">Submit</button>-->
                    <a data-id="{{ produit.id }}" class="acheter-produit"><button>Acheter</button></a>
                    <!--<input type="submit" value="ACHETER" data-action="add" data-id="{{ legume.id }}" class="acheter-produit">-->
                </form>
                
            </div>
            {% empty %}
            <div class="col-md-12 aeftcu" style="text-align: center;">
                
                <p style="font-size: 1.5rem;">Aucun résultat pour "{{ query }}"</p>
                <a href="{% url 'marche:accueil' %}" class="btn btn-primary waves-effect waves-light">Retour à l'accueil</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

marche/templates/marche/supcategorie.html
{% extends 'marche/main.html' %}
{% load humanize %}
{% load static %}

{% block description %}{{ supcategorie.description }} {% endblock %}
<title>{% block title %}{% for cat in categorie %} {{ cat.nom }}{% endfor %} - Samamarché {% endblock %} </title>

{% block carousel %}
{% endblock %}
{% block content %}

    <!-- Legumes block -->
    
    {% for cat in categorie %}
    <div class="container" style="padding-top: 10px;">
        <a name="{{ cat.slug }}" class="title_categ"></a>
        <div class="row">
            <div class="col-md-12" id="categ">
            
            <h2 class="text-dark" id="{{ cat.slug }}">{{ cat.nom }}</h2>
            
          </div>
        </div>
    </div>

    <div class="lkight">
    <div class="container produit produits"> 
        <div class="row">   
           
            {% for produit in cat.get_produits %} 
            <div class="col-md-2 col-xs-3 col-sm-3 col-6 lkightpro">
                {% if produit.image %}
                <img src="{{ produit.image.url }}" class="w-100ce w-100cee" alt="">
                {% else %}
                <img src="{% static 'images/courge.jpg' %}" class="w-100ce w-100cee" alt="">
                {% endif %}
                <h5 class="my-3">{{ produit.nom }}</h5>
                <span class="my-3">{{ produit.prix | intcomma }} FCFA/{{ produit.prix | intcomma }}</span>
                
                <form action="{% url "cart:cart_add" produit.id %}" method="post" class="form-order" data-id="{{ produit.id }}" >
                    {{ cart_produit_form_cat }}
                    {% csrf_token %}
                    <a data-id="{{ produit.id }}" class="acheter-produit"><button>ACHETER</button></a>
                </form>   
            </div>
            {% endfor %}
       
        </div>
        </div> 
          
    </div>

    {% endfor %}
    <!--End legumes block-->

    
       
{% endblock %}