cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('cart', views.cart_detail, name='cart_detail'),
    path('add/<int:produit_id>/', views.ajouter_cart, name='cart_add'),
    path('update/<int:produit_id>/', views.update_cart, name='cart_update'),
    
    
    path('remove/<int:produit_id>', views.supprimer_cart, name='cart_remove'),
]

commandes/urls.py
from django.urls import path
from . import views

app_name = 'commandes'

urlpatterns = [
    path('creer', views.creer_commande, name='creer_commande'),
   
    path('ajax/load-quartiers', views.load_quartiers, name='ajax_load_quartiers'),
    path('mes-commandes', views.commandes_user, name='mes_commandes'),
    path('<int:commande_id>', views.commandes_detail, name='detail_commande')
]

marche/urls.py
from django.urls import path
from . import views

app_name = 'marche'

urlpatterns = [
    path('', views.accueil, name='accueil'),
	path('search', views.post_search, name='post_search'),
	#path('<slug:categorie_slug>/', views.produits_par_categorie, name='produit_par_categorie'),
	path('<slug:supcategorie_slug>', views.produits_par_supcategorie, name='produit_par_supcategorie'),
	path('<int:id>/<slug:slug>', views.produit_detail, name='produit_detail'),
	

]

samamarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users import views as user_views

from users import views

#from users.views import RegistrationView, ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('marche.urls')),

    path('cart/', include('cart.urls')),

    path('commandes/', include('commandes.urls')),

    path('coupons/', include('coupons.urls')),

    #path('register/', user_views.register, name='register'),
    #path('profile/', user_views.profile, name='profile'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    #path('commandes/login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    #path('register/', RegistrationView.as_view(), name='register'),
    path('register/', user_views.register, name='register'),
    #path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/profile', user_views.profile, name='profile'),
    #path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('accounts/login/', user_views.signin, name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('accounts/password_change/', user_views.change_password, name='password_change'),
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/done/', user_views.change_password_done, name='password_change_done'),

    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset'),
    path('password_reset/', user_views.password_reset_request, name='password_reset'),
    path('password_reset_instructions/', user_views.instructions_reset_page, name='passwordinstructions'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', user_views.password_reset_confirme, name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]
handler404 = 'marche.views.error_404'

handler500 = 'marche.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commandes/models.py
from django.db import models
from marche.models import Produit
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

class Departement(models.Model):
    nom = models.CharField(max_length=200)

    def __str__(self):
        return self.nom
        

class Quartier(models.Model):
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    nom = models.CharField(max_length=200)
    prix_livraison = models.IntegerField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_maj = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom
    
    def get_prix_livraison(self):
        return self.prix_livraison
        

class Commande(models.Model):
    STATUS_CHOICES = (
        ('Effectué', 'Commande effectuée'),
        ('En cours', 'Commande en cours de traitement'),
        ('Livrée', 'Commande livrée')
    )
    utilisateur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    prenom = models.CharField(max_length=250)
    nom = models.CharField(max_length=100)
    email = models.EmailField()
    indication = models.CharField(max_length=250, null=True)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    quartier = models.ForeignKey(Quartier, on_delete=models.CASCADE)
    telephone = PhoneNumberField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_maj = models.DateTimeField(auto_now=True)
    payement = models.BooleanField(default=False)
    etat = models.CharField(max_length=255,
                            choices=STATUS_CHOICES,
                            default='Commande effectuée')
    date_livraison = models.DateTimeField(null=True)

    
    class Meta:
        ordering = ('-date_creation',)

    def __str__(self):
        return 'Commande {}'.format(self.id)

    def get_cout_total(self):
        return sum(item.get_prix() for item in self.items.all())

    def get_commande(self):
        pass



class CommandeItem(models.Model):
    commande = models.ForeignKey(Commande, related_name='items', on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit,
                                related_name='order_items',
                                on_delete=models.CASCADE
    )
    prix = models.IntegerField()
    quantite = models.IntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)
    
    def get_prix(self):
        return self.prix * self.quantite

commandes/forms.py
from django import forms
from .models import Commande, Quartier

STATUS_CHOICES = (
    ('payement_livraison', 'Payer à la livraison'),
    ('payement_intouch', 'Payer par Orange Money ou par carte bancaire'),
    ('cart_bancaire', 'Payer par carte bancaire ')
)

class CommandeCreationForm(forms.ModelForm):
    modes_de_payement = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect(attrs={'required': True, 'class':'payment_methods'}))
    class Meta:
        model = Commande
        fields = ('prenom', 'nom', 'email', 'telephone', 'departement', 'quartier', 'indication', 'modes_de_payement')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quartier'].queryset = Quartier.objects.none()
        self.fields['prenom'].widget.attrs['placeholder'] = 'Prénom'
        self.fields['nom'].widget.attrs['placeholder'] = 'Nom'
        self.fields['email'].widget.attrs['placeholder'] = 'Votre email'
        self.fields['telephone'].widget.attrs['placeholder'] = 'Numéro de téléphone'
        self.fields['indication'].widget.attrs['placeholder'] = "Exemple: En face de l'école Dior"
        self.fields['indication'].required = False
        
        if 'departement' in self.data:
            try:
                departement_id = int(self.data.get('departement'))
                self.fields['quartier'].queryset = Quartier.objects.filter(departement_id=departement_id).order_by('nom')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['quartier'].queryset = self.instance.departement.quartier_set.order_by('nom') 

        if 'departement' not in self.data:
            try:
                departement_id = None
                self.fields['quartier'].queryset = Quartier.objects.none()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset

commandes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import CommandeItem, Commande, Quartier
from .forms import CommandeCreationForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.detail import SingleObjectMixin
from django.conf import settings
from users.models import User
from .tasks import commande_cree
from marche.models import Info
from marche.forms import SearchForm
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget, PhoneNumberPrefixWidget
# Create your views here.

info = Info.objects.all()[:1]
searchform = SearchForm
@login_required(login_url='login')
def creer_commande(request):
    cart = Cart(request)
    #commandes = Commande.objects.filter(utilisateur=request.user)[0]
    #if commandes.exists():
    user = request.user
    initial_data = {
            'prenom': request.user.prenom,
            'nom' : request.user.nom,
            'email': request.user.email,
            'telephone': request.user.telephone
    }
    if request.method == 'POST':

        form = CommandeCreationForm(request.POST or None)
        user = request.user
        if form.is_valid():
            commande = form.save(commit=False)
            commande.utilisateur = request.user
            commande = form.save(commit=False)
            #commande.save(commit=False)
            commandi = form.cleaned_data['quartier'].prix_livraison

            prix_livraison = 500

            mode_payment = request.POST.get('modes_de_payement')

            #commandi = cart.get_prix_total() + prix_livraison
            if mode_payment == 'payement_livraison':
                commande = form.save()
                for item in cart:
                    CommandeItem.objects.create(commande=commande,
                                                produit=item['produit'], 
                                                prix=item['prix'], 
                                                quantite=item['quantite'])
                                                
                # Clear the cart
                #cart.clear()
          
            #commande_cree.delay(commande.id)
            context = {
                'commande': commande,
                'cart': cart,
                'prenom': commandi,
                'info': info,
                'searchform': SearchForm,
            }
            return render(request, 'commandes/commande-cree.html', {'commande': commande, 'cart': cart, 'prenom': commande})

            if mode_payment == 'payement_intouch':
                pass
    else:
        initial_data = {
            'prenom': request.user.prenom,
            'nom' : request.user.nom,
            'email': request.user.email,
            'telephone': request.user.telephone
        }
        context = {
            'form': CommandeCreationForm(initial_data),
            'cart': cart,
            'info': info,
            'searchform': SearchForm,
        }
    return render(request, 'commandes/creer-commande.html', context)



def load_quartiers(request):
    departement_id = request.GET.get('departement')
    cities = Quartier.objects.filter(departement_id=departement_id).order_by('nom')
    return render(request, 'commandes/quartiers_dropdown_list_options.html', {'cities': cities})


@login_required(login_url='login')
def commandes_user(request):
    user = request.user
    cart = Cart(request)
    commandes = Commande.objects.filter(utilisateur=user)
    context = {
        'commandes_user': commandes,
        'user': user,
        'info': info,
        'searchform': SearchForm,
        'cart': cart,
    }
    return render(request, 'commandes/mes-commandes.html', context)


@login_required(login_url='login')
def commandes_detail(request, commande_id):
    user = request.user.email
    cart = Cart(request)
    if request.user.email == user:
        commande = get_object_or_404(Commande, id=commande_id, utilisateur=request.user)
        items = CommandeItem.objects.all().filter(commande__id=commande_id)
        context = {
            'commande': commande,
            'items': items,
            'searchform': SearchForm,
            'cart': cart,
            'info': info,
        }

        return render(request, 'commandes/details.html', context)
    else:
        return redirect('marche:accueil')

commandes/templates/commandes/commande-cree.html
{{ commande }}
{{ cart }}
abc
{{ prenom }}

commandes/templates/commandes/commande_form.html
{% extends 'marche/main.html' %}

{% block carousel %}{% endblock %}
{% block content %}


  <h2>Person Form</h2>

  <form method="post" id="commandeForm" data-cities-url="{% url "commandes:ajax_load_quartiers" %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Commander</button>
    
  </form>

{% endblock %}

commandes/templates/commandes/commande_list.html
plo

{{ object_list }}

{{ some_data }} {{ abc }}

{{ contexte }}

{{ cart.cart }}

commandes/templates/commandes/creer-commande.html
{% extends "marche/main.html" %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block carousel %}
{% endblock %}
{% block content %}
{% if cart|length > 0 %}
<div class="container  aeftcu">
  <div class="row">
  <div class="col-md-8">
      <div>
          <h3 style="color:#212121!important;">Coordonnées client</h3>
      </div>
      <form action="" method="post" class="order-form" id="commandeForm" data-cities-url="{% url "commandes:ajax_load_quartiers" %}">
          {{ form|crispy }}
          </br>
          <p><input type="submit" class="btn btn-primary waves-effect waves-light adress-liv" value="Commander"></p>
          {% csrf_token %}
      </form>
  </div>
  <div class="col-md-4">
    <ul class="list-group mb-3">
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Nombre d'articles</h6>
          <small class="text-muted"></small>
        </div>
        <span class="badge badge-success">{{ cart | length }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Sous-total</h6>
          <small class="text-muted"></small>
        </div>
        <span class="text-muted" id="data-prix" data-price-total="{{ cart.get_prix_total_apres_reduction }}">{{ cart.get_prix_total_apres_reduction | intcomma }} FCFA</span>
      </li>
      {% if cart.coupon %}
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Code de réduction</h6>
          <small class="text-muted"></small>
        </div>
        <span class="text-muted" id="">{{ cart.coupon.code }} ({{ cart.coupon.reduction }}% off)</span>
      </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Prix de livraison</h6>
          <small class="text-muted"></small>
        </div>
        <span class="text-muted" id="prix_livraison">Non disponible</span>
      </li>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Prix total</h6>
          <small class="text-muted">avec le prix de livraison</small>
        </div>
        <span class="text-muted" id="prix_total">Non disponible</span>
      </li>
      
    </ul>
  </div>
</div>
</div>
{% else %}
<div class="container to_register">
  <div class="row">
    <div class="col-md-12" style="text-align: center;">
      <i class="bx bxs-cart icon-single empty-icon-cart" style="font-size: 6rem;"></i>
      <p style="font-size: 1.5rem;">Votre panier est vide</p>
      <a href="{% url 'marche:accueil' %}" class="btn btn-primary waves-effect waves-light">Faire vos courses</a>
    </div>
  </div>
</div>
    
{% endif %}
{% endblock %}

commandes/templates/commandes/details.html
{% extends "marche/main.html" %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block carousel %}
{% endblock %}
{% block content %}

<div class="container aeftcu">
    <div class="row">
        <div class="col-md-4">
            <ul class="list-group mb-3">
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <a href="{% url 'profile' %}"><h6 class="my-0">Mon compte</h6></a>
                  <small class="text-muted"></small>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <a href="{% url 'commandes:mes_commandes' %}"><h6 class="my-0">Mes commandes</h6></a>
                  <small class="text-muted"></small>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <a href="#"><h6 class="my-0">Codes promo disponibles</h6></a>
                  <small class="text-muted"></small>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <a href="{% url 'password_change' %}"><h6 class="my-0">Modifier mon de passe</h6></a>
                </div>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <a href="{% url 'logout' %}"><h6 class="my-0">Se déconnecter</h6></a>
                </div>
              </li>
              
            </ul>
        </div>
        
        <div class="col-md-8">
          <div class="">
            <h5 class="register-title">
              Détails de la commande
              <small class="text-muted"></small>
            </h5>
            <h6 class="chytt">
              Commande n° {{ commande.id}}
              <small class="text-muted"></small>
            </h6>
          </div>
          
          <table>
            <tr>
              <th class="clp_app chytt">Date de création</th>
              <td class="clp_ap my-3 chytt">{{ commande.date_creation }}</td>
            </tr>

            {% if commande.date_livraison %}
            <tr>
              <th class="clp_app chytt">Date de livraison </th>
              <td class="clp_ap my-3 chytt">{{ commande.date_livraison }}</td>
            </tr>
            {% else %}
            <tr>
              <th class="clp_app chytt">Date de livraison </th>
              <td class="clp_ap my-3 chytt">Date indisponible</td>
            </tr>
            {% endif %}

            <tr>
              <th class="clp_app chytt">Sous-total</th>
              <td class="clp_ap my-3 chytt">{{ commande.get_cout_total|intcomma }} FCFA</td>
            </tr>
            <tr>
              <th class="clp_app chytt">Prix de livraison</th>
              <td class="clp_ap my-3 chytt">{{ commande.quartier.prix_livraison|intcomma }} FCFA</td>
            </tr>
            <tr>
              <th class="clp_app chytt">Total </th>
              <td class="clp_ap my-3 chytt">{{ commande.quartier.prix_livraison|intcomma }} FCFA</td>
            </tr>
            <tr>
              <th class="clp_app chytt">Etat</th>
              {% if commande.etat == "Effectué" %}
                <td class="clp_ap my-3 clp_eff chytt" style="color: white!important;">{{ commande.etat }}</td>
              {% elif commande.etat == "En cours" %}
                <td class="clp_ap my-3 clp_encours chytt" style="color: white!important;">{{ commande.etat }}</td>
              {% elif commande.etat == "Livrée" %}
                <td class="clp_ap my-3 clp_livre chytt" style="color: white!important;">{{ commande.etat }}</td>
              {% endif %}
            </tr>
          </table>
        </br>
         
        <h5 class="register-title">Produits de la commande</h5>
          
          <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col" colspan="2" class="clp_app chytt">Produit</th>
                <th scope="col" class="clp_app chytt">Prix</th>
                <th scope="col" class="clp_app chytt">Quantité</th>
                <th scope="col" class="clp_app chytt">Total</th>
              </tr>
            </thead>
            <tbody>
              {% for item in commande.items.all %}
              <tr>
                <th scope="row"><img class="row-image" src="{% static 'images/courge.jpg' %}"></th>
                <td class="clp_app chytt">{{ item.produit.nom }} </td>
                <td class="clp_app chytt">{{ item.prix|intcomma }}</td>
                <td class="clp_app chytt">{{ item.quantite }}</td>
                <td class="clp_app chytt">{{ item.get_prix|intcomma }} FCFA</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>

        </div>
    </div>
</div>

{% endblock %}

commandes/templates/commandes/incident-modal.html
eneida marta

commandes/templates/commandes/logine.html
{% extends "marche/main.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="row col-md-4 offset-md-4">
  <div class="col-md-12 formulaire">
      <form action="" method="post">
        taarutaaru@outlook.fr
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="md-12">Se connnecter</legend>
              {{ form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-info" type="submit">Se connecter</button>
          </div>
      </form>
  </div>
</div>
{% endblock %}

commandes/templates/commandes/mes-commandes.html
{% extends "marche/main.html" %}
{% load crispy_forms_tags %}
{% block carousel %}
{% endblock %}
{% block content %}

<div class="container aeftcu">
    <div class="row">
        <div class="col-md-4">
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <a href="{% url 'profile' %}"><h6 class="my-0">Mon compte</h6></a>
                <small class="text-muted"></small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <a href="{% url 'commandes:mes_commandes' %}"><h6 class="my-0">Mes commandes</h6></a>
                <small class="text-muted"></small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <a href="#"><h6 class="my-0">Codes promo disponibles</h6></a>
                <small class="text-muted"></small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <a href="{% url 'password_change' %}"><h6 class="my-0">Modifier mon de passe</h6></a>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <a href="{% url 'logout' %}"><h6 class="my-0">Se déconnecter</h6></a>
              </div>
            </li>
            
          </ul>
        </div>
        <div class="col-md-8">
            <h4 class="register-title">Mes commandes</h4>
            <ul class="list-group mb-3">
                {% for commande in commandes_user %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div>
                    <a href="{% url 'commandes:detail_commande' commande_id=commande.id %}" data-popup-url="{% url 'commandes:detail_commande' commande_id=commande.id %}" class="open-incident">
                      <h6 class="my-0">Commande du {{ commande.date_creation }}</h6>
                    </a>
                    <small class="text-muted"></small>
                  </div>
                </li>
                {% endfor %}
                <!--
                {% include "commandes/incident-modal.html" %}-->
                
              </ul>
        </div>

        
    </div>
</div>

{% endblock %}

commandes/templates/commandes/quartiers_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}" data-price="{{ city.prix_livraison }}">{{ city.nom }}</option>

{% endfor %}